platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'KEImageMergeView' do
  pod 'Loaf'
	pod 'IBAnimatable'
	pod 'Alamofire'
	pod 'Kingfisher'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
